apiVersion: v1
kind: Service
metadata:
  name: southsystem-importer-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    component: southsystem-importer

